const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: "$20",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Medium Shirt",
      slug: "nike-medium-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: "$30",
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: "$10",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pant",
    },
    {
      name: "Nike casual Pant",
      slug: "nike-casual-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: "$50",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pant",
    },
  ],
};
export default data;
